[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = '5t111111/alt-gtags.vim'

[[plugins]]
repo = 'derekwyatt/vim-scala.git'
on_ft = ['scala']

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'
