- name:
  command: >
    defaults write {{ item.domain }} {{ item.key }} -{{ item.type }} {{ item.value }}
  with_items:
  - {
        domain: com.apple.ImageCapture,
        key: disableHotPlug,
        type: bool,
        value: false,
    }
  - {
        domain: com.apple.dock,
        key: wvous-bl-corner,
        type: int,
        value: 10,
    }

- name:
  command: >
    defaults write -g {{ item.key }} -{{ item.type }} {{ item.value }}
  with_items:
    - {
        key: InitialKeyRepeat,
        type: int,
        value: 15,
      }
    - {
        key: KeyRepeat,
        type: int,
        value: 1,
      }


